name: "Bug report"
description: Report errors or unexpected behavior
labels:
- Issue-Bug
- Needs-Triage
body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](https://github.com/microsoft/PowerToys/issues) before filing a new one!
- type: input
  attributes:
    label: Efected MyTel-U Version
    placeholder: Input versio number here for example (1.0.0)
    description: You can find it on the setting page inside the aplication
  validations:
    required: true

- type: input
  attributes:
    label: What Windows version are you using?
    placeholder: Input the data here
    description: You can find it by hovering over the start icon (the Windows Logo on the taskbar), right-clicking, and then selecting 'System'. You can input the data under 'Device Specification' and 'Windows Specification' here. Alternatively (and this is recommended), you can also press 'Windows + R' on your keyboard, type "dxdiag" into the run dialog, then hit enter. Choose 'Save All Information', then drag and drop the file into your issue, or attach it through the file selection dialog.

- type: input
  attributes:
    label: Expected bug behaviour
  validations:
    required: true

- type: input
  attributes:
    label: Steps to reproduce the bug
    description: Please describe the steps you took to reproduce the bug, providing as much detail as possible.
  validations:
    required: true
