name: "Feature Request"
description: This is a feature request section. 
labels:
- Issue-Feature
- Needs-Triage
body:
- type: markdown
  attributes:
    value: Thank you for taking the time to suggest a new feature for this application. Your input is valuable to us. Please follow the form provided below to submit your feature request.

- type: input
  attributes:
    label: Feature Description
    placeholder: Describe the feature you'd like to see implemented
    description: Please provide a clear and concise description of what the feature is and what it would do.
  validations:
    required: true

- type: input
  attributes:
    label: Why is this feature important?
    placeholder: Explain why this feature would be beneficial
    description: Please provide some context about why this feature would be helpful. How would it improve the application?
  validations:
    required: true

- type: input
  attributes:
    label: Any ideas on how to implement this feature?
    placeholder: Share your ideas on how this feature could be implemented
    description: If you have ideas about how this feature could be implemented, please share them here. If not, that's okay too!
  validations:
    required: false

- type: input
  attributes:
    label: Additional context or screenshots
    description: If you have any additional context or screenshots about the feature request, please share them here.
    placeholder: attach the image here
  validations:
    required: false
